language: ruby

rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=mysql

bundler_args:
  - --quiet
  
before_script:
  - curl -Lo config/database.yml https://raw.github.com/gist/38c55d9ffaf6f9865949/database.yml
  - RAILS_ENV=development bundle exec rake db:{setup,test:prepare} stats
  - bundle exec rails_best_practices --spec -x schema,devise,secret

script:
  - bundle exec rspec spec

notifications:
  email: false
