language: ruby

rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=mysql

bundler_args:
  - --quiet

before_script:
  - curl -Lo config/database.yml http://git.io/YLiX3g
  - bundle
  - bundle exec rake db:setup stats

script:
  - RAILS_ENV=test bundle exec rspec spec
