language: ruby

rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=mysql

before_script:
  - curl -Lo config/database.ci.yml https://raw.github.com/gist/38c55d9ffaf6f9865949/database.yml
  - bundle exec rake db:setup

script:
  - bundle exec rake spec
